name: openapi-to-postman-action
description: Publish OpenAPI Specification (OAS) to Postman Collection
author: Diego Conti Santeri Tonini <diegosanteri@gmail.com>, Hans Chun <hanschun>, Fluximus, Inc.
branding:
  icon: arrow-up-circle
  color: blue
inputs: # user can input the name inside the name of user variable , descriptions etc
  postmanCollectionUid:
    description: 'Postman Collection UID'
    required: true
    default: 'String'
  postmanApiKey:
    description: 'Postman API Key'
    required: true
    default: 'String'
  openApiSpec:
    description: 'It can be an url or the file'
    required: true
    default: 'String'
runs: 
  using: 'node20'
  main: 'dist/index.js'

